### ISSUE TITLE
Updated version?

### ISSUE THREAD

**Issue by Phillip-May** [abdelq/lode-runner#3]
Is there a more up to date version of this? The current version doesn't send x and y positions every time next() is called and dosen't call start when a new level is reached?

**Comment by abdelq** [comment]
The actual version on Github is the latest.

> The current version doesn't send x and y positions every time next() is called and dosen't call start when a new level is reached?

I'm not sure what you are talking about. I just tried it quickly with the Javascript client and it outputs coordinates on every `next` and calls `start` on a new level. The issue is most likely on your side in the client.
It might be worth to try to debug it. PRs are welcome.

**Comment by Phillip-May** [comment]
My apologies, I tried it from a different computer and it worked fine. I suspect the problem is self engineered from trying to run the server in a virtual machine and connecting to it from the host.
